# Generated by Django 2.2.3 on 2019-07-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_extra_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='extrasauce',
            field=models.BooleanField(default=True),
        ),
    ]
