# Generated by Django 2.2.3 on 2019-07-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_extra_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='comboprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
