# Generated by Django 2.2.3 on 2019-07-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190728_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='extrasauce',
            field=models.BooleanField(default=False),
        ),
    ]
