# Generated by Django 2.2.3 on 2019-07-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190728_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
