# Generated by Django 2.2.3 on 2019-07-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_extra_many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='fbyatt', to='orders.Extra'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='foods', to='orders.Categories'),
        ),
    ]
