# Generated by Django 2.2.3 on 2019-07-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190728_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(related_name='foods', to='orders.Categories'),
        ),
    ]
