# Generated by Django 2.2.3 on 2019-07-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_eachitem_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eachitem',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='carteditem', to='orders.Extra'),
        ),
    ]
