# Generated by Django 2.2.3 on 2019-07-30 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190729_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='usernameid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
