# Generated by Django 2.2.3 on 2019-07-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20190729_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='eachitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
